language: python

matrix:
  include:
    - python: 3.5
      env: DEPS="pandas=0.24 matplotlib=1.4.3 cython getdist"
    - python: 3.8
      env: DEPS="coveralls matplotlib pandas cython getdist"
install:
  - pip install "$DEPS"
  - python setup.py install

script:
  # run tests
  - coverage run setup.py test

after_success: coveralls
